blueprint:
  name: Hydro-Québec Flex D (Événements de calendrier)
  description: '# Gestion des événements de pointe critique "Flex D" via calendrier.


    Ce blueprint utilise les événements de calendrier créés automatiquement par l''intégration
    Hydro-Québec pour déclencher vos automatisations lors des périodes de pointe critique.


    **Prérequis** : Vous devez avoir configuré un calendrier dans les options de
    votre intégration Hydro-Québec Flex-D (DPC).


    ## Configuration


    ### Sélection du calendrier

    Sélectionnez le calendrier que vous avez configuré dans l''intégration Hydro-Québec
    pour recevoir les événements de pointe critique.


    ### Période de pré-chauffage

    Définissez combien de temps avant le début de l''événement vous souhaitez commencer
    le pré-chauffage de votre résidence (en minutes).


    ### Actions


    Définition des actions à effectuer dans Home-Assistant lors de chaque début et
    fin de périodes.


    **Important** : Pour éviter qu''une erreur dans une action empêche l''exécution
    des actions suivantes, il est recommandé d''utiliser des appels d''actions en
    parallèle. Exemple : au lieu d''une séquence simple, utilisez `parallel:` pour
    grouper vos actions.


    ### Métadonnées disponibles


    Les événements de calendrier incluent des métadonnées accessibles dans vos actions :

    - trigger.calendar_event.summary : Titre (🔴 Pointe critique / ⚪ Pointe régulière)

    - trigger.calendar_event.location : Tarif (Hydro-Québec DPC)

    - trigger.calendar_event.description : Contient Critique: Oui/Non, Tarif: DPC, etc.


    **Exemple de condition** pour filtrer uniquement les pointes critiques :

    condition: template / value_template: "{{ ''Critique: Oui'' in trigger.calendar_event.description }}"


    Vous trouverez plus de détails sur les logiques applicables pour Flex-D

    dans la [documentation Hydroqc](https://hydroqc.ca/fr/docs/tarification-dynamique/).

    '
  domain: automation
  input:
    hydroqc_calendar:
      name: Calendrier Hydro-Québec
      description: Sélectionnez le calendrier configuré dans l'intégration Hydro-Québec pour les événements de pointe critique
      selector:
        entity:
          domain: calendar
          multiple: false
    preheat_offset:
      name: Délai de pré-chauffage
      description: "Temps avant le début de l'événement pour commencer le pré-chauffage (format HH:MM:SS, ex: -02:00:00 pour 2 heures avant)"
      default: "-02:00:00"
      selector:
        duration:
          enable_day: false
    pre_heat_start_action:
      name: Action de pré-chauffage
      description: Actions à effectuer avant la période de pointe critique pour
        pré-chauffer votre résidence.
      default: []
      selector:
        action: {}
    critical_peak_start_action:
      name: Action début pointe critique
      description: Actions à effectuer au début de la période de pointe critique pour
        réduire votre consommation électrique.
      default: []
      selector:
        action: {}
    critical_peak_end_action:
      name: Action fin pointe critique
      description: Actions à effectuer à la fin de la période de pointe critique pour
        rétablir votre consommation normale.
      default: []
      selector:
        action: {}
  source_url: https://github.com/hydroqc/hydroqc-ha/blob/main/blueprints/flex-d-calendar.yaml
mode: parallel
trigger:
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: !input preheat_offset
    id: pre_heat_trigger
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    id: peak_start_trigger
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: end
    id: peak_end_trigger
# Add condition to filter only peak events (title contains "pointe") and DPC rate
condition:
  - condition: template
    value_template: "{{ 'pointe' in trigger.calendar_event.summary | lower }}"
  - condition: template
    value_template: "{{ 'DPC' in trigger.calendar_event.location }}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: pre_heat_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input pre_heat_start_action
      - conditions:
          - condition: trigger
            id: peak_start_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_peak_start_action
      - conditions:
          - condition: trigger
            id: peak_end_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_peak_end_action
    default:
      - parallel: []
