blueprint:
  name: Hydro-Québec Crédits Hivernaux (Événements de calendrier)
  description: |
    # Gestion des événements de crédit hivernal via calendrier.

    Ce blueprint utilise les événements de calendrier créés automatiquement par l'intégration Hydro-Québec pour déclencher vos automatisations lors des périodes de pointe critique et non-critique (si configuré).

    **Prérequis** : Vous devez avoir configuré un calendrier dans les options de votre intégration Hydro-Québec D+CPC (Crédits Hivernaux).

    ## Configuration

    ### Sélection du calendrier

    Sélectionnez le calendrier que vous avez configuré dans l'intégration Hydro-Québec pour recevoir les événements de pointe.

    ### Période de pré-chauffage

    Définissez combien de temps avant le début de l'événement vous souhaitez commencer le pré-chauffage de votre résidence (en minutes).

    ### Périodes d'ancrage
    Les périodes d'ancrage sont des périodes de notification avant les pointes :
    - Pointes du matin (AM, 6h-10h) : Ancrage débute 5h avant, se termine 2h avant la pointe
    - Pointes du soir (PM, 16h-20h) : Ancrage débute 4h avant, se termine 2h avant la pointe

    Ce blueprint utilise des déclencheurs multiples pour capturer toutes les combinaisons possibles. Les valeurs par défaut couvrent les deux cas (matin et soir), déclenchant aux moments appropriés selon l'événement de calendrier.

    ### Actions

    Définition des actions à effectuer dans Home-Assistant lors de chaque début et fin de périodes.

    **Important** : Pour éviter qu'une erreur dans une action empêche l'exécution des actions suivantes, il est recommandé d'utiliser des appels d'actions en parallèle. Exemple : au lieu d'une séquence simple, utilisez `parallel:` pour grouper vos actions.

    **Workflows complexes** : Si vous avez besoin de logiques conditionnelles complexes ou de nombreuses étapes, il est recommandé d'utiliser ce blueprint pour déclencher des automatisations séparées plutôt que d'inclure toute la logique ici. Cela facilite la maintenance et le débogage.

    **Note** : Ce blueprint différencie automatiquement les pointes critiques et non-critiques selon les métadonnées de l'événement. Vous pouvez définir des actions différentes pour chaque type de pointe.


    ### Métadonnées disponibles

    Les événements de calendrier incluent des métadonnées accessibles dans vos actions :

    - trigger.calendar_event.summary : Titre (🔴 Pointe critique / ⚪ Pointe régulière)
  
    - trigger.calendar_event.description : Contient Critique: Oui/Non, Tarif: DCPC, etc.

    **Le blueprint détecte automatiquement** si une pointe est critique en vérifiant
    la présence de "Critique: Oui" dans la description de l''événement.

    ### Création manuelle d'événements

    Si l'intégration ne crée pas automatiquement les événements (API indisponible, problème de configuration), vous pouvez créer manuellement des événements dans votre calendrier :

    1. Créez un événement aux heures de pointe (6h-10h ou 16h-20h)
    2. Titre: "🔴 Pointe critique" ou "⚪ Pointe régulière"
    3. Description:
    ```
    Tarif: DCPC
    Critique: Oui (ou Non)
    ```
 
    Vous trouverez plus de détails sur les logiques applicables pour les crédits hivernaux dans la [documentation Hydro-Québec](https://hydroqc.ca/fr/docs/tarification-dynamique/).
  domain: automation
  input:
    hydroqc_calendar:
      name: Calendrier Hydro-Québec
      description: Sélectionnez le calendrier configuré dans l'intégration Hydro-Québec pour les événements de pointe
      selector:
        entity:
          domain: calendar
          multiple: false
    preheat_offset:
      name: Délai de pré-chauffage
      description: "Temps avant le début de l'événement pour commencer le pré-chauffage (format -HH:MM:SS, ex: -02:00:00 pour 2 heures avant, -01:30:00 pour 1h30 avant)"
      default: "-02:00:00"
      selector:
        text:
          type: text
    critical_peak_offset:
      name: Délai avant début pointe critique
      description: "Temps avant le début officiel de la pointe pour déclencher les actions (permet aux appareils de se stabiliser avant la pointe). Format -HH:MM:SS, ex: -00:01:00 pour 1 minute avant"
      default: "-00:01:00"
      selector:
        text:
          type: text
    
    # ===== ACTIONS ESSENTIELLES =====
    # Actions pour les pointes CRITIQUES (prioritaires)
    critical_pre_heat_start_action:
      name: "[Critique] Action pré-chauffage"
      description: 'Actions pour pointes CRITIQUES - avant pointe (défaut 2h). Ex: Maximisez chauffage pour atteindre température élevée.'
      default:
        - parallel:
            - alias: Action 1
              # Votre action ici
            - alias: Action 2
              # Votre action ici
      selector:
        action: {}
    critical_peak_start_action:
      name: "[Critique] Action début pointe"
      description: 'Actions pour pointes CRITIQUES - début pointe (6h/16h). Ex: Réduction agressive - fermez chauffe-eau, minimisez CVAC.'
      default:
        - parallel:
            - alias: Action 1
              # Votre action ici
            - alias: Action 2
              # Votre action ici
      selector:
        action: {}
    critical_peak_end_action:
      name: "[Critique] Action fin pointe"
      description: |
        Actions pour pointes CRITIQUES - fin pointe (10h/20h). Ex: Rétablissez tous appareils à opération normale.
        
        **Délai aléatoire par défaut (30 sec - 5 min)** : Évite une surcharge du réseau électrique causée par le redémarrage simultané de milliers d'appareils à la fin de la pointe. Si vous avez plusieurs actions de reprise, ajoutez un délai aléatoire similaire entre chacune pour étaler la consommation.
      default:
        - delay:
            seconds: "{{ range(30, 300)|random|int }}"
          alias: Délai aléatoire 30 sec - 5 minutes
      selector:
        action: {}
    
    # ===== ACTIONS OPTIONNELLES =====
    # Actions pour les pointes RÉGULIÈRES (non-critiques)
    regular_peak_actions:
      name: "⚪ Actions pointes régulières (optionnel)"
      description: "Actions pour les pointes non-critiques. Ces pointes font partie de l'horaire régulier (tous les jours en hiver) et ne sont généralement pas annoncées par Hydro-Québec."
      collapsed: true
      input:
        regular_peak_start_action:
          name: "[Régulière] Début pointe"
          description: 'Pointes RÉGULIÈRES - début pointe (6h/16h). Ex: Réduction légère - baisse temp, reportez charges non-essentielles.'
          default: []
          selector:
            action: {}
        regular_peak_end_action:
          name: "[Régulière] Fin pointe"
          description: 'Pointes RÉGULIÈRES - fin pointe (10h/20h). Ex: Rétablissez réglages normaux.'
          default: []
          selector:
            action: {}
    
    # ===== ACTIONS OPTIONNELLES (ANCRAGE) =====
    # Période d'ancrage - permet d'établir une consommation de référence
    anchor_actions:
      name: "⚙️ Actions d'ancrage (optionnel)"
      description: "Les actions d'ancrage permettent d'établir une consommation de référence avant les pointes. Ces actions sont optionnelles."
      collapsed: true
      input:
        critical_anchor_start_morning_action:
          name: "[Critique] Début ancrage matin"
          description: 'Pointes CRITIQUES - 5h avant pointe matin (1h). Maintenez consommation normale.'
          default: []
          selector:
            action: {}
        critical_anchor_start_evening_action:
          name: "[Critique] Début ancrage soir"
          description: 'Pointes CRITIQUES - 4h avant pointe soir (12h). Maintenez consommation normale.'
          default: []
          selector:
            action: {}
        critical_anchor_end_morning_action:
          name: "[Critique] Fin ancrage matin"
          description: 'Pointes CRITIQUES - 2h avant pointe matin (4h). Fin ancrage.'
          default: []
          selector:
            action: {}
        critical_anchor_end_evening_action:
          name: "[Critique] Fin ancrage soir"
          description: 'Pointes CRITIQUES - 2h avant pointe soir (14h). Fin ancrage.'
          default: []
          selector:
            action: {}
        regular_anchor_start_morning_action:
          name: "[Régulière] Début ancrage matin"
          description: 'Pointes RÉGULIÈRES - 5h avant pointe matin (1h). Maintenez normal.'
          default: []
          selector:
            action: {}
        regular_anchor_start_evening_action:
          name: "[Régulière] Début ancrage soir"
          description: 'Pointes RÉGULIÈRES - 4h avant pointe soir (12h). Maintenez normal.'
          default: []
          selector:
            action: {}
        regular_anchor_end_morning_action:
          name: "[Régulière] Fin ancrage matin"
          description: 'Pointes RÉGULIÈRES - 2h avant pointe matin (4h). Fin ancrage.'
          default: []
          selector:
            action: {}
        regular_anchor_end_evening_action:
          name: "[Régulière] Fin ancrage soir"
          description: 'Pointes RÉGULIÈRES - 2h avant pointe soir (14h). Fin ancrage.'
          default: []
          selector:
            action: {}
  source_url: https://github.com/hydroqc/hydroqc-ha/blob/main/blueprints/winter-credits-calendar.yaml
mode: parallel
trigger:
  # Morning anchor start: 5 hours before (for AM peaks, e.g., 1h for 6h peak)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: "-5:00:00"
    id: anchor_start_morning_trigger
  # Evening anchor start: 4 hours before (for PM peaks, e.g., 12h for 16h peak)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: "-4:00:00"
    id: anchor_start_evening_trigger
  # Morning anchor end: 2 hours before AM peak (e.g., 4h for 6h peak)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: "-2:00:00"
    id: anchor_end_morning_trigger
  # Evening anchor end: 2 hours before PM peak (e.g., 14h for 16h peak)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: "-2:00:00"
    id: anchor_end_evening_trigger
  # Pre-heat start: configurable offset before peak
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: !input preheat_offset
    id: pre_heat_trigger
  # Critical peak start: configurable offset before official peak start (default 1min before)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    offset: !input critical_peak_offset
    id: critical_peak_start_trigger
  # Regular peak start (no offset)
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: start
    id: regular_peak_start_trigger
  # Peak end
  - platform: calendar
    entity_id: !input hydroqc_calendar
    event: end
    id: peak_end_trigger
# Add condition to filter only peak events (title contains "pointe")
condition:
  - condition: template
    value_template: "{{ 'pointe' in trigger.calendar_event.summary | lower }}"
action:
  - choose:
      # Morning anchor start - CRITICAL
      - conditions:
          - condition: trigger
            id: anchor_start_morning_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_anchor_start_morning_action
      # Morning anchor start - REGULAR
      - conditions:
          - condition: trigger
            id: anchor_start_morning_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_anchor_start_morning_action
      
      # Evening anchor start - CRITICAL
      - conditions:
          - condition: trigger
            id: anchor_start_evening_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_anchor_start_evening_action
      # Evening anchor start - REGULAR
      - conditions:
          - condition: trigger
            id: anchor_start_evening_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_anchor_start_evening_action
      
      # Morning anchor end - CRITICAL
      - conditions:
          - condition: trigger
            id: anchor_end_morning_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_anchor_end_morning_action
      # Morning anchor end - REGULAR
      - conditions:
          - condition: trigger
            id: anchor_end_morning_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_anchor_end_morning_action
      
      # Evening anchor end - CRITICAL
      - conditions:
          - condition: trigger
            id: anchor_end_evening_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_anchor_end_evening_action
      # Evening anchor end - REGULAR
      - conditions:
          - condition: trigger
            id: anchor_end_evening_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_anchor_end_evening_action
      
      # Pre-heat - CRITICAL ONLY (regular peaks don't have preheat)
      - conditions:
          - condition: trigger
            id: pre_heat_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_pre_heat_start_action
      
      # Peak start - CRITICAL (with offset before official start)
      - conditions:
          - condition: trigger
            id: critical_peak_start_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_peak_start_action
      # Peak start - REGULAR (at official start time)
      - conditions:
          - condition: trigger
            id: regular_peak_start_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_peak_start_action
      
      # Peak end - CRITICAL
      - conditions:
          - condition: trigger
            id: peak_end_trigger
          - condition: template
            value_template: "{{ 'Critique: Oui' in trigger.calendar_event.description }}"
        sequence: !input critical_peak_end_action
      # Peak end - REGULAR
      - conditions:
          - condition: trigger
            id: peak_end_trigger
          - condition: template
            value_template: "{{ 'Critique: Non' in trigger.calendar_event.description }}"
        sequence: !input regular_peak_end_action
    default:
      - parallel: []
